name: foraos-backend
services:
- name: api
  source_dir: /
  github:
    repo: monarchoct/ForaOS
    branch: main
  run_command: node railway-backend.js
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: ELEVENLABS_API_KEY
    scope: RUN_TIME
    type: SECRET
