name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Create API keys config
        run: |
          mkdir -p config
          echo "Creating API keys config..."
          echo "OpenAI key length: ${#OPENAI_API_KEY}"
          echo "ElevenLabs key length: ${#ELEVENLABS_API_KEY}"
          cat > config/api-keys.json << EOF
          {
            "openai": {
              "apiKey": "${{ secrets.OPENAI_API_KEY || 'your-openai-api-key-here' }}",
              "model": "gpt-3.5-turbo",
              "maxTokens": 150,
              "temperature": 0.8
            },
            "elevenlabs": {
              "apiKey": "${{ secrets.ELEVENLABS_API_KEY || 'your-elevenlabs-api-key-here' }}",
              "baseUrl": "https://api.elevenlabs.io/v1"
            },
            "twitter": {
              "apiKey": "${{ secrets.TWITTER_API_KEY || 'your-twitter-api-key' }}",
              "apiSecret": "${{ secrets.TWITTER_API_SECRET || 'your-twitter-api-secret' }}",
              "accessToken": "${{ secrets.TWITTER_ACCESS_TOKEN || 'your-twitter-access-token' }}",
              "accessTokenSecret": "${{ secrets.TWITTER_ACCESS_TOKEN_SECRET || 'your-twitter-access-token-secret' }}",
              "bearerToken": "${{ secrets.TWITTER_BEARER_TOKEN || 'your-twitter-bearer-token' }}"
            },
            "twitch": {
              "clientId": "${{ secrets.TWITCH_CLIENT_ID || 'your-twitch-client-id' }}",
              "clientSecret": "${{ secrets.TWITCH_CLIENT_SECRET || 'your-twitch-client-secret' }}",
              "accessToken": "${{ secrets.TWITCH_ACCESS_TOKEN || 'your-twitch-access-token' }}"
            }
          }
          EOF
          echo "API keys config created successfully"
        
      - name: Build
        run: npm run web-build
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
